config/routes.rb
DeployReporter::Application.routes.draw do

  root :to => 'projects#index'

  resources :projects, :only => [:index, :show] do
    resources :deployments, :only => :index
    resources :incidents, :only => :index
  end

  resources :deployments, :only => [:index, :show, :create] do
    resources :incidents, :only => :new
  end

  resources :incidents, :only => :index

end

app/models/deployment.rb
class Deployment < ActiveRecord::Base
  belongs_to :project
  validates :deployer,    :presence => true
  validates :deployed_at, :presence => true

  before_validation(:on => :create) do
    self.deployed_at ||= DateTime.now.utc
  end

  def project_name
    project.name
  end

  def project_name=(project_name)
    if project
      project.name = project_name
    else
      self.project = Project.find_or_create_by_name(project_name)
    end
  end

  def deployed_on
    deployed_at.to_date
  end

end

app/models/incident.rb
class Incident < ActiveRecord::Base
  validates :occurred_at, :presence => true
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :deployments
  validates :name, :presence => true, :uniqueness => true

  def deploy_rate
    return 0.0 if 0 == (deployment_date_count = deploy_count_by_date.size)
    deploy_count_by_date.inject(0.0) { |sum, count| sum + count } / deployment_date_count
  end

  def incident_rate
    0.0203
  end

  def deploy_count
    deployments.size
  end

  private

  def deploy_count_by_date
    @deploy_count_by_date ||= deployments.group_by(&:deployed_on).values.map(&:length)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/deployments_controller.rb
class DeploymentsController < ApplicationController

  before_filter :load_project, :only => :index

  def index
    @deployments = Deployment.includes(:project)
    @deployments = @deployments.where(:project_id => @project.id) if @project
    @deployments = DeploymentDecorator.decorate(@deployments)
  end

  def show
    @deployment = DeploymentDecorator.find(params[:id])
  end

  def create
    @deployment = Deployment.create!(params[:deployment])
    render :nothing => true
  end

  protected

  def load_project
    @project = Project.find(params[:project_id]) if params[:project_id]
  end

end

app/controllers/incidents_controller.rb
class IncidentsController < ApplicationController

  def index
    @incidents = IncidentDecorator.decorate(Incident.all)
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = ProjectDecorator.decorate(Project.all)
  end

  def show
    @project = ProjectDecorator.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/deployments/index.html.erb
<%- @deployments.group_by(&:deployed_at_as_date).sort { |a,b| b.first <=> a.first }.each do |date, deployments| %>
		<div class='table_header grid_4 suffix_12'><%= date.mon %>/<%= date.day %></div>
		<table id='deployments-<%= date.strftime('%F') %>' class='container_16'>
			<%- deployments.sort { |a,b| a.deployed_at <=> b.deployed_at }.each do |deployment| %>
				<tr id='<%= deployment.to_view_id %>'>
					<td class='grid_4'><%= link_to deployment.deployed_at_timestamp, deployment %></td>
					<td class='grid_4'><%= link_to deployment.project_name, deployment.project %></td>
					<td class='grid_4'><%= deployment.deployer %></td>
					<td class='grid_4'>
						<%= deployment.description_summary %><%= link_to '...', deployment %>
					</td>
				</tr>
			<%- end %>
		</table>
    <div class='clear'></div>
<%- end %>

app/views/deployments/show.html.erb
<%= @deployment.project_name %>
<%= @deployment.deployed_at_timestamp(:full) %>
<%= @deployment.deployer %>
<%= @deployment.description %>
<%= link_to 'Report an incident', new_deployment_incident_path(@deployment) %>

app/views/incidents/index.html.erb
<%- @incidents.group_by(&:occurred_at).each do |occurred_at, incidents| %>
	<table id='incidents-<%= occurred_at.strftime('%Y-%m-%d').strip %>'>
		<%- incidents.each do |incident| %>
			<tr id='<%= incident.to_view_id %>'>
				<td><%= incident.occurred_at_timestamp %></td>
				<td><%= incident.time_to_detect_in_words %></td>
				<td><%= incident.time_to_diagnose_in_words %></td>
				<td><%= incident.time_to_resolve_in_words %></td>
				<td>
					<%= link_to '', '#', :class => 'severity orange', :alt => 'There were errors'                       if incident.had_errors? %>
					<%= link_to '', '#', :class => 'severity orange', :alt => 'A redeployment was required'             if incident.required_redeploy? %>
					<%= link_to '', '#', :class => 'severity red',    :alt => 'A rollback was required'                 if incident.required_rollback? %>
					<%= link_to '', '#', :class => 'severity red',    :alt => 'Noticed outside of the development team' if incident.noticed_outside_of_development? %>
					<%= link_to '', '#', :class => 'severity red',    :alt => 'A formal incident report was required'   if incident.required_formal_incident_report? %>
				</td>
			</tr>
		<%- end %>
	</table>
<%- end %>

app/views/layouts/application.html.erb
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!-- Consider adding a manifest.appcache: h5bp.com/d/Offline -->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <!-- Use the .htaccess and remove these lines to avoid edge case issues.
       More info: h5bp.com/b/378 -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title>DeployReporter</title>
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Mobile viewport optimized: j.mp/bplateviewport -->
  <meta name="viewport" content="width=device-width,initial-scale=1">

  <!-- Place favicon.ico and apple-touch-icon.png in the root directory: mathiasbynens.be/notes/touch-icons -->

  <%= stylesheet_link_tag 'application' %>
  <%= csrf_meta_tags %>

  <!-- More ideas for your <head> here: h5bp.com/d/head-Tips -->

  <!-- All JavaScript at the bottom, except this Modernizr build incl. Respond.js
       Respond is a polyfill for min/max-width media queries. Modernizr enables HTML5 elements & feature detects;
       for optimal performance, create your own custom Modernizr build: www.modernizr.com/download/ -->
  <%= javascript_include_tag 'modernizr' %>
</head>

<body>
  <div id='wrapper' class='container_16'>
    <header class='grid_16'>
      <%= link_to 'Projects', projects_path %>
      <%= link_to 'Deployments', deployments_path %>
      <%= link_to 'Incidents', incidents_path %>
    </header>
    <%= yield %>
  </div>

  <!-- JavaScript at the bottom for fast page loading -->
  <%= javascript_include_tag 'application' %>
  <!-- end scripts -->


  <!-- Asynchronous Google Analytics snippet. Change UA-XXXXX-X to be your site's ID.
       mathiasbynens.be/notes/async-analytics-snippet -->
  <script>
    var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview'],['_trackPageLoadTime']];
    (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
    g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
    s.parentNode.insertBefore(g,s)}(document,'script'));
  </script>

  <!-- Prompt IE 6 users to install Chrome Frame. Remove this if you want to support IE 6.
       chromium.org/developers/how-tos/chrome-frame-getting-started -->
  <!--[if lt IE 7 ]>
    <script defer src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.3/CFInstall.min.js"></script>
    <script defer>window.attachEvent('onload',function(){CFInstall.check({mode:'overlay'})})</script>
  <![endif]-->

</body>
</html>

app/views/projects/index.html.erb
<div class='table_header grid_4 suffix_4'>Projects</div>
<table id='projects' class='container_16'>
	<%- @projects.each do |project| %>
	<tr id='<%= project.to_view_id %>'>
		<td class='grid_4'><%= link_to project.name, project %></td>
		<td class='grid_4'><%= link_to project.deploy_count, [project, :deployments] %></td>
		<td class='grid_4'><%= project.deploy_rate %></td>
		<td class='grid_4'><%= link_to project.incident_rate_fraction, [project, :incidents] %></td>
	</tr>
	<%- end %>
</table>

app/views/projects/show.html.erb
<%= @project.name %>
<div id='deploy_count'><%= @project.deploy_count %></div>
<div id='deploy_rate'><%= @project.deploy_rate %></div>
<div id='incident_rate'><%= @project.incident_rate_fraction %></div>
<%= link_to 'Deployments', [@project, :deployments] %>
<%= link_to 'Incidents', [@project, :incidents] %>